### ISSUE TITLE
Windows Server 2016 CIS 1.4.0 - 18.8.21.5 issue with logic

### ISSUE THREAD

**Issue by SteffenWinternheimer** [fbprogmbh/Audit-Test-Automation#324] opened 2023-04-05 08:40 UTC
The following rule will always return false, please check this test 
![grafik](https://user-images.githubusercontent.com/35689334/230024435-4b8e12de-fe04-49c6-981d-c92e36591767.png)

**Comment by qngngyn** [comment] 2023-10-09 06:31
This ticket is no longer relevant. The checks are working as intended. Closing the thread.

**Closed by qngngyn** 2023-10-09 06:31 UTC
