### ISSUE TITLE
[PR2] Add dependency for all ASR rules in case Windows Defender is not used

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#216] opened 2023-01-20 16:52 UTC
We need a optimization and only flag ASR rules green or red in case WIndows Defender is up and running. In case not the rules must not be marked as "true" or "false".

**Comment by TuemmlerKelch** [comment] 2023-01-23 09:57
Duplicate of #147

**Comment by TuemmlerKelch** [comment] 2023-01-23 14:11
I checked this on ATAP 5.3 and apparently we need to also add the following check, as ASR rules only matter when this returns False: (Get-MpPreference).Disablerealtimemonitoring

**Closed** 2023-02-03 08:29 UTC
Labels: enhancement
